// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_netbsd.go

package pty

type ptmget struct {
	Cfd int32
	Sfd int32
	Cn  [1024]int8
	Sn  [1024]int8
}

var ioctl_TIOCPTMGET = 0x48087446
